### ISSUE TITLE
[schematron-pure] universalTests2.sch results in to many assertion messages

### ISSUE THREAD

**Issue by Katzor** [phax/ph-schematron#152] opened 2023-06-07 11:29 UTC
ph-schematron-testfiles; external/test-sch/universalTests2.sch; external/test-xml/valid03.xml

In universalTests2.sch it says: "The result of running this should be four assertion messages: U7, U8, U9, and U10 only."

schematron-sch results in these four assertion messages.

schematron-pure results in 8 assertion messages:

U5: This assertion should never succeed because the rule should never fire.
U6: This report should never succeed because the rule should never fire.
U7: This assertion should always fail.
U8: This report should always succeed.
U9: This assertion should always fail.
U10: This report should always succeed.
U11: This assertion should never succeed because the rule should never fire.
U12: This report should never succeeed because the rule should never fire.

**Comment by phax** [comment] 2023-06-07 13:21
Yes indeed it's a duplicate of this issue. The reason is the different resolution model in pure - it does NOT follow the "XSLT way" by visiting each element just once. Instead it behaves like each rule is independent from the pattern it is used in.

Maybe we should really define a separate query binding "java-pure" to solve all these incompatibilities...

**Comment by phax** [comment] 2024-02-15 16:38
I am closing this as a duplicate of #84 - however they are still linked, so we're not losing anything

**Closed by phax** 2024-02-15 16:38 UTC
Labels: duplicate, Implementation pure
